name: Deploy pages
on:
    push:
        branches:
          - main
jobs:
    deploy:
        runs-on: docker://pandoc/core:2.12
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: pandoc_all
              shell: bash
              working-directory: ./
              run: python3 ../../pandoc_all.py
            - name: deploy
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                branch: gh-pages
                folder: output
